# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list
    silent: true

  dev:
    desc: Start dev environment
    cmds:
      - air -c .air.toml
    silent: true

