name: "Lint PR"

on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v5
      with:
        requireScope: false
        types: |
          fix
          feat
          fix!
          feat!
          chore
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
