name: Validate PR Title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: lab42/ccu-action@main
        with:
          pr_title: ${{ github.event.pull_request.title }}
